/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./pages/**/*.{js,jsx}",
        "./components/**/*.{js,jsx}",
        "./app/**/*.{js,jsx}",
        "./src/**/*.{js,jsx}",
    ],
    prefix: "",
    theme: {
        container: {
            center: true,
            padding: "2rem",
            screens: {
                "2xl": "1400px",
            },
        },
        extend: {
            fontFamily: {
                sans: ['Lexend', 'system-ui', 'sans-serif'],
                display: ['Alata', 'sans-serif'],
                body: ['Lexend', 'system-ui', 'sans-serif'],
                quicksand: ['Quicksand', 'system-ui', 'sans-serif'],
                nunito: ['Nunito', 'system-ui', 'sans-serif'],
            },
            colors: {
                border: "rgb(var(--border) / <alpha-value>)",
                input: "rgb(var(--input) / <alpha-value>)",
                ring: "rgb(var(--ring) / <alpha-value>)",
                background: "rgb(var(--background) / <alpha-value>)",
                foreground: "rgb(var(--foreground) / <alpha-value>)",
                primary: {
                    DEFAULT: "rgb(var(--primary) / <alpha-value>)",
                    foreground: "rgb(var(--primary-foreground) / <alpha-value>)",
                },
                secondary: {
                    DEFAULT: "rgb(var(--secondary) / <alpha-value>)",
                    foreground: "rgb(var(--secondary-foreground) / <alpha-value>)",
                },
                destructive: {
                    DEFAULT: "rgb(var(--destructive) / <alpha-value>)",
                    foreground: "rgb(var(--destructive-foreground) / <alpha-value>)",
                },
                success: {
                    DEFAULT: "rgb(var(--success) / <alpha-value>)",
                    foreground: "rgb(var(--success-foreground) / <alpha-value>)",
                },
                warning: {
                    DEFAULT: "rgb(var(--warning) / <alpha-value>)",
                    foreground: "rgb(var(--warning-foreground) / <alpha-value>)",
                },
                muted: {
                    DEFAULT: "rgb(var(--muted) / <alpha-value>)",
                    foreground: "rgb(var(--muted-foreground) / <alpha-value>)",
                },
                accent: {
                    DEFAULT: "rgb(var(--accent) / <alpha-value>)",
                    foreground: "rgb(var(--accent-foreground) / <alpha-value>)",
                },
                popover: {
                    DEFAULT: "rgb(var(--popover) / <alpha-value>)",
                    foreground: "rgb(var(--popover-foreground) / <alpha-value>)",
                },
                card: {
                    DEFAULT: "rgb(var(--card) / <alpha-value>)",
                    foreground: "rgb(var(--card-foreground) / <alpha-value>)",
                },
                sidebar: {
                    DEFAULT: "rgb(var(--sidebar-background) / <alpha-value>)",
                    foreground: "rgb(var(--sidebar-foreground) / <alpha-value>)",
                    primary: "rgb(var(--sidebar-primary) / <alpha-value>)",
                    "primary-foreground": "rgb(var(--sidebar-primary-foreground) / <alpha-value>)",
                    accent: "rgb(var(--sidebar-accent) / <alpha-value>)",
                    "accent-foreground": "rgb(var(--sidebar-accent-foreground) / <alpha-value>)",
                    border: "rgb(var(--sidebar-border) / <alpha-value>)",
                    ring: "rgb(var(--sidebar-ring) / <alpha-value>)",
                },
                role: {
                    student: "rgb(var(--role-student) / <alpha-value>)",
                    organizer: "rgb(var(--role-organizer) / <alpha-value>)",
                    judge: "rgb(var(--role-judge) / <alpha-value>)",
                    admin: "rgb(var(--role-admin) / <alpha-value>)",
                },
                // New color palettes
                'deep-twilight': {
                    50: 'rgb(var(--color-deep-twilight-50) / <alpha-value>)',
                    100: 'rgb(var(--color-deep-twilight-100) / <alpha-value>)',
                    200: 'rgb(var(--color-deep-twilight-200) / <alpha-value>)',
                    300: 'rgb(var(--color-deep-twilight-300) / <alpha-value>)',
                    400: 'rgb(var(--color-deep-twilight-400) / <alpha-value>)',
                    500: 'rgb(var(--color-deep-twilight-500) / <alpha-value>)',
                    600: 'rgb(var(--color-deep-twilight-600) / <alpha-value>)',
                    700: 'rgb(var(--color-deep-twilight-700) / <alpha-value>)',
                    800: 'rgb(var(--color-deep-twilight-800) / <alpha-value>)',
                    900: 'rgb(var(--color-deep-twilight-900) / <alpha-value>)',
                    950: 'rgb(var(--color-deep-twilight-950) / <alpha-value>)',
                },
                'french-blue': {
                    50: 'rgb(var(--color-french-blue-50) / <alpha-value>)',
                    100: 'rgb(var(--color-french-blue-100) / <alpha-value>)',
                    200: 'rgb(var(--color-french-blue-200) / <alpha-value>)',
                    300: 'rgb(var(--color-french-blue-300) / <alpha-value>)',
                    400: 'rgb(var(--color-french-blue-400) / <alpha-value>)',
                    500: 'rgb(var(--color-french-blue-500) / <alpha-value>)',
                    600: 'rgb(var(--color-french-blue-600) / <alpha-value>)',
                    700: 'rgb(var(--color-french-blue-700) / <alpha-value>)',
                    800: 'rgb(var(--color-french-blue-800) / <alpha-value>)',
                    900: 'rgb(var(--color-french-blue-900) / <alpha-value>)',
                    950: 'rgb(var(--color-french-blue-950) / <alpha-value>)',
                },
                'bright-teal-blue': {
                    50: 'rgb(var(--color-bright-teal-blue-50) / <alpha-value>)',
                    100: 'rgb(var(--color-bright-teal-blue-100) / <alpha-value>)',
                    200: 'rgb(var(--color-bright-teal-blue-200) / <alpha-value>)',
                    300: 'rgb(var(--color-bright-teal-blue-300) / <alpha-value>)',
                    400: 'rgb(var(--color-bright-teal-blue-400) / <alpha-value>)',
                    500: 'rgb(var(--color-bright-teal-blue-500) / <alpha-value>)',
                    600: 'rgb(var(--color-bright-teal-blue-600) / <alpha-value>)',
                    700: 'rgb(var(--color-bright-teal-blue-700) / <alpha-value>)',
                    800: 'rgb(var(--color-bright-teal-blue-800) / <alpha-value>)',
                    900: 'rgb(var(--color-bright-teal-blue-900) / <alpha-value>)',
                    950: 'rgb(var(--color-bright-teal-blue-950) / <alpha-value>)',
                },
                'blue-green': {
                    50: 'rgb(var(--color-blue-green-50) / <alpha-value>)',
                    100: 'rgb(var(--color-blue-green-100) / <alpha-value>)',
                    200: 'rgb(var(--color-blue-green-200) / <alpha-value>)',
                    300: 'rgb(var(--color-blue-green-300) / <alpha-value>)',
                    400: 'rgb(var(--color-blue-green-400) / <alpha-value>)',
                    500: 'rgb(var(--color-blue-green-500) / <alpha-value>)',
                    600: 'rgb(var(--color-blue-green-600) / <alpha-value>)',
                    700: 'rgb(var(--color-blue-green-700) / <alpha-value>)',
                    800: 'rgb(var(--color-blue-green-800) / <alpha-value>)',
                    900: 'rgb(var(--color-blue-green-900) / <alpha-value>)',
                    950: 'rgb(var(--color-blue-green-950) / <alpha-value>)',
                },
                'turquoise-surf': {
                    50: 'rgb(var(--color-turquoise-surf-50) / <alpha-value>)',
                    100: 'rgb(var(--color-turquoise-surf-100) / <alpha-value>)',
                    200: 'rgb(var(--color-turquoise-surf-200) / <alpha-value>)',
                    300: 'rgb(var(--color-turquoise-surf-300) / <alpha-value>)',
                    400: 'rgb(var(--color-turquoise-surf-400) / <alpha-value>)',
                    500: 'rgb(var(--color-turquoise-surf-500) / <alpha-value>)',
                    600: 'rgb(var(--color-turquoise-surf-600) / <alpha-value>)',
                    700: 'rgb(var(--color-turquoise-surf-700) / <alpha-value>)',
                    800: 'rgb(var(--color-turquoise-surf-800) / <alpha-value>)',
                    900: 'rgb(var(--color-turquoise-surf-900) / <alpha-value>)',
                    950: 'rgb(var(--color-turquoise-surf-950) / <alpha-value>)',
                },
                'sky-aqua': {
                    50: 'rgb(var(--color-sky-aqua-50) / <alpha-value>)',
                    100: 'rgb(var(--color-sky-aqua-100) / <alpha-value>)',
                    200: 'rgb(var(--color-sky-aqua-200) / <alpha-value>)',
                    300: 'rgb(var(--color-sky-aqua-300) / <alpha-value>)',
                    400: 'rgb(var(--color-sky-aqua-400) / <alpha-value>)',
                    500: 'rgb(var(--color-sky-aqua-500) / <alpha-value>)',
                    600: 'rgb(var(--color-sky-aqua-600) / <alpha-value>)',
                    700: 'rgb(var(--color-sky-aqua-700) / <alpha-value>)',
                    800: 'rgb(var(--color-sky-aqua-800) / <alpha-value>)',
                    900: 'rgb(var(--color-sky-aqua-900) / <alpha-value>)',
                    950: 'rgb(var(--color-sky-aqua-950) / <alpha-value>)',
                },
                'frosted-blue': {
                    50: 'rgb(var(--color-frosted-blue-50) / <alpha-value>)',
                    100: 'rgb(var(--color-frosted-blue-100) / <alpha-value>)',
                    200: 'rgb(var(--color-frosted-blue-200) / <alpha-value>)',
                    300: 'rgb(var(--color-frosted-blue-300) / <alpha-value>)',
                    400: 'rgb(var(--color-frosted-blue-400) / <alpha-value>)',
                    500: 'rgb(var(--color-frosted-blue-500) / <alpha-value>)',
                    600: 'rgb(var(--color-frosted-blue-600) / <alpha-value>)',
                    700: 'rgb(var(--color-frosted-blue-700) / <alpha-value>)',
                    800: 'rgb(var(--color-frosted-blue-800) / <alpha-value>)',
                    900: 'rgb(var(--color-frosted-blue-900) / <alpha-value>)',
                    950: 'rgb(var(--color-frosted-blue-950) / <alpha-value>)',
                },
                'light-cyan': {
                    50: 'rgb(var(--color-light-cyan-50) / <alpha-value>)',
                    100: 'rgb(var(--color-light-cyan-100) / <alpha-value>)',
                    200: 'rgb(var(--color-light-cyan-200) / <alpha-value>)',
                    300: 'rgb(var(--color-light-cyan-300) / <alpha-value>)',
                    400: 'rgb(var(--color-light-cyan-400) / <alpha-value>)',
                    500: 'rgb(var(--color-light-cyan-500) / <alpha-value>)',
                    600: 'rgb(var(--color-light-cyan-600) / <alpha-value>)',
                    700: 'rgb(var(--color-light-cyan-700) / <alpha-value>)',
                    800: 'rgb(var(--color-light-cyan-800) / <alpha-value>)',
                    900: 'rgb(var(--color-light-cyan-900) / <alpha-value>)',
                    950: 'rgb(var(--color-light-cyan-950) / <alpha-value>)',
                },
                'neutral': {
                    50: 'rgb(var(--color-neutral-50) / <alpha-value>)',
                    100: 'rgb(var(--color-neutral-100) / <alpha-value>)',
                    200: 'rgb(var(--color-neutral-200) / <alpha-value>)',
                    300: 'rgb(var(--color-neutral-300) / <alpha-value>)',
                    400: 'rgb(var(--color-neutral-400) / <alpha-value>)',
                    500: 'rgb(var(--color-neutral-500) / <alpha-value>)',
                    600: 'rgb(var(--color-neutral-600) / <alpha-value>)',
                    700: 'rgb(var(--color-neutral-700) / <alpha-value>)',
                    800: 'rgb(var(--color-neutral-800) / <alpha-value>)',
                    900: 'rgb(var(--color-neutral-900) / <alpha-value>)',
                    950: 'rgb(var(--color-neutral-950) / <alpha-value>)',
                },
            },
            borderRadius: {
                lg: "var(--radius)",
                md: "calc(var(--radius) - 2px)",
                sm: "calc(var(--radius) - 4px)",
            },
            boxShadow: {
                'soft': 'var(--shadow-md)',
                'elevated': 'var(--shadow-lg)',
                'prominent': 'var(--shadow-xl)',
                'glow': 'var(--shadow-glow)',
            },
            backgroundImage: {
                'gradient-primary': 'var(--gradient-primary)',
                'gradient-hero': 'var(--gradient-hero)',
                'gradient-card': 'var(--gradient-card)',
                'gradient-accent': 'var(--gradient-accent)',
            },
            keyframes: {
                "accordion-down": {
                    from: { height: "0" },
                    to: { height: "var(--radix-accordion-content-height)" },
                },
                "accordion-up": {
                    from: { height: "var(--radix-accordion-content-height)" },
                    to: { height: "0" },
                },
                "fade-in": {
                    from: { opacity: "0" },
                    to: { opacity: "1" },
                },
                "fade-up": {
                    from: { opacity: "0", transform: "translateY(20px)" },
                    to: { opacity: "1", transform: "translateY(0)" },
                },
                "scale-in": {
                    from: { opacity: "0", transform: "scale(0.95)" },
                    to: { opacity: "1", transform: "scale(1)" },
                },
            },
            animation: {
                "accordion-down": "accordion-down 0.2s ease-out",
                "accordion-up": "accordion-up 0.2s ease-out",
                "fade-in": "fade-in 0.5s ease-out forwards",
                "fade-up": "fade-up 0.6s ease-out forwards",
                "scale-in": "scale-in 0.4s ease-out forwards",
            },
        },
    },
    plugins: [require("tailwindcss-animate")],
};
